- OpenLiveWriter.SDK.nuspec
- OpenLiveWriter.nuspec
> Issue #18 - Fix link to license in NUSPEC files

- src/managed/OpenLiveWriter.BlogClient/Clients/LiveJournalClient.cs
returning invalid arg for "0" value on Gal…lery security setting.  Changed to 255 (public) per documentation
> Fix #49 as LiveJournal API 

- src/managed/OpenLiveWriter.ApplicationFramework/ApplicationWorkspaceColumnLightweightControl.cs
- src/managed/OpenLiveWriter.ApplicationFramework/CommandContextManager.cs
- src/managed/OpenLiveWriter.ApplicationFramework/CommandContextMenu.cs
- src/managed/OpenLiveWriter.ApplicationFramework/TabLightweightControl.cs
- src/managed/OpenLiveWriter.ApplicationFramework/WorkspaceColumnLightweightControl.cs
Just fixing up a little silly stuff I saw.
> Removing my name and some spelling errors. Nothing substantial.

- faq.md
By moving the FAQ from the wiki to the repo, this enables people to submit pull requests against the frequently asked questions (FAQ.)
> Copies FAQ from wiki into repo

- src/managed/OpenLiveWriter.BlogClient/Clients/LiveJournalClient.cs
- src/managed/OpenLiveWriter.BlogClient/Providers/BlogProvidersB5.xml
Fixes for #80 (enabling AtomClient for OLW) and #54 (removing some branding).
> Fix #80 and #54

- src/managed/PostBuild.CreateInstaller/createinstaller.cmd
Fixes #27
I think this is Good Enough™ but let me know if I've missed something about the deployment process.
> rename the installer file to be more descriptive

- CONTRIBUTING.md
- README.md
Add a basic CONTRIBUTOR.md file so that it will get displayed when people create new issues or pull requests.
@kathweaver - appreciate your help making this better once we have got the initial version in.
> Add contributor guidance file

- src/managed/OpenLiveWriter.PostEditor/Configuration/Wizard/WeblogConfigurationWizardPanelSharePointAuthentication.cs
Small adjustment in Tab Index of the Connection Wizard for SharePoint
> Tab Index Adjustment

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
Make sure we round-trip the labels from posts stored on the server (see #164)
> Roundtrip Blogger labels

- src/managed/OpenLiveWriter.PostEditor/WeblogCommandManager.cs
> Refresh the list of blogs when one is removed/added

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
The OAuth access token expires quickly (every hour) and we get an HTTP 403 error code when we attempt to call a Picasa API with an expired access token. The BloggerService class provided by the Google API Client library for .NET takes care of automatically refreshing the access token when calling the Blogger API. This is not true of our Picasa integration, which features direct HTTP requests to the Picasa API endpoint, so I've added code to catch the HTTP 403 error code and force refresh the access token.
> Issue #170 - The remote server returned an error: (403) Forbidden.

- src/managed/OpenLiveWriter.HtmlEditor/HtmlEditorControl.cs
- src/managed/OpenLiveWriter.Mshtml/MarkupPointer.cs
> Fix MoveAdjacentToElement Error

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
> Issue #221: Make sure a null list isn't used.

- src/managed/OpenLiveWriter.CoreServices/WebRequest/PageAndReferenceDownloader.cs
Don't attempt to download embedded images.
> added code to not attempt to download base64 embeded images

- testplan/observeFileTab.md
- testplan/observeInsertTab.md
- testplan/observeOpenProgram.md
Added test plans for File Tab, Insert Tab and for observing the program
which it first opens.
> Added test plans

- src/managed/OpenLiveWriter.Localization/DisplayMessages.xml
- src/managed/OpenLiveWriter.Localization/Properties.resx
- src/managed/OpenLiveWriter.PostEditor/ImageInsertion/WebImages/WebImageForm.cs
- src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/ImageEditing/ImageEditingPropertyHandler.cs
This is a work in progress relating to #103
> Fix error #103 when inserting image from web

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
> Fix ArgumentNullException

- testplan/testVideo/insertVideoFromFile.md
- testplan/testVideo/insertVideoFromVideoService.md
- testplan/testVideo/insertVideoFromWeb.md
- testplan/testVideo/observeVideoDialogBox.md
While I know that the video isn't working correctly in Open Live Writer, the test plans were
created by observing the original Live Writer behavior.
> Added Video Tests Plans

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
We weren't including the correct API parameters to request drafts and
scheduled posts from Google Blogger. When getting the list of posts and
pages, we need to do 2-3 requests with different parameters and combine
the results. For getting individual posts and pages, we had to specify
view permissions in the request.
> Issue #298 - Show drafts and scheduled posts and pages for Google Blogger

- src/managed/OpenLiveWriter.ApplicationFramework/OpenLiveWriter.ApplicationFramework.csproj
- src/managed/OpenLiveWriter.InternalWriterPlugin/OpenLiveWriter.InternalWriterPlugin.csproj
This is to address #403. The code base seems to come from .NET Framework 1.1 where the necessary tags are missing in project files.
> Fixed the missing <DependentUpon> tags in project files.

- README.md
Created a new branch because something happened to the other one and I couldn't fix it.
> Added Build Instructions to README

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
> guard against CategoryArray being null

- src/managed/OpenLiveWriter.Controls/BitmapButton.cs
- src/managed/OpenLiveWriter.PostEditor/PostPropertyEditing/CategoryControl/TreeCategorySelector.cs
> Fix scaling of categories dropdown and options dialog

- .gitignore
- src/managed/BlogRunner.Core/BlogRunner.Core.csproj
- src/managed/BlogRunner.Core/packages.config
- src/managed/BlogRunner/BlogRunner.csproj
- src/managed/BlogRunner/packages.config
- src/managed/BlogRunnerGui/BlogRunnerGui.csproj
- src/managed/BlogRunnerGui/packages.config
- src/managed/OpenLiveWriter.PostEditor/AboutForm.cs
- src/managed/OpenLiveWriter.Tests/OpenLiveWriter.Tests.csproj
- src/managed/OpenLiveWriter.UnitTest/OpenLiveWriter.UnitTest.csproj
- src/managed/OpenLiveWriter.UnitTest/packages.config
- src/managed/OpenLiveWriter/OpenLiveWriter.csproj
- src/managed/OpenLiveWriter/packages.config
Hi,
one time I looked for a link in the about box too.
So I added one.
Regards
Michael
> #441 added homepage link to the about screen

- src/managed/OpenLiveWriter.CoreServices/OpenLiveWriter.CoreServices.csproj
- src/managed/writer.sln
- writer.build.targets
Avoid unnecessary rebuilding of marketization files
Should help a bit with #446
> Only create Blogger json file if necessary

- OpenLiveWriter.Install.nuspec
- choco/LICENSE.TXT
- choco/VERIFICATION.TXT
> (GH-790) Added necessary files for embedded Chocolatey Package

- src/managed/OpenLiveWriter.HtmlEditor/HtmlSourceEditorControl.cs
- src/managed/OpenLiveWriter.PostEditor/ContentEditor/ContentEditor.cs
- src/managed/OpenLiveWriter.PostEditor/PostEditorPreferences.cs
- src/managed/OpenLiveWriter.PostEditor/PostEditorPreferencesPanel.cs
- src/managed/OpenLiveWriter.PostEditor/PostEditorPreferencesPanel.resx
- src/managed/OpenLiveWriter.PostEditor/PostEditorSettings.cs
- src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/BlogPostHtmlSourceEditorControl.cs
Added option to always format that HTML that shows up in the "source" view. This makes it easier to read and edit the HTML for the post.
> Option to always format HTML

- OpenLiveWriter.nuspec
> ssg: Add YamlDotNet to nuspec

- README.md
This is what was already done on OpenLiveWriter.Github.io README.
> Update README.md to point to .com instead of .org
