OpenLiveWriter/OpenLiveWriter

- .gitignore
This ignores the VC.opendb file that is created in VS2015 Update 1 with C++ projects
> Adding VC.opendb to ignore file

- src/managed/PostBuild.CreateInstaller/createinstaller.cmd
Fix postinstaller to be more tolerant: (i) Use quote marks to ensure spaces in the user profile directory (e.g. C:\Users\Tim Sneath) don't break the batch file; (ii) fail more gently if Nuget.exe isn't in the %localappdata% directory, since it's not installed by default with Visual Studio.
> Be more tolerant of dev workstation environment

- src/managed/OpenLiveWriter.PostEditor/AboutForm.cs
We use some awesome bits of open source like Squirrel, Splat, Mono.Cecil & DeltaCompressionDotNet - add links to them in the AboutForm.
I'd like for the AboutForm to be a lot nicer (I think the GitHub Desktop does a really good job with theirs) but this is a quick hack to make sure we at least give them some props and make sure folks can easily see where to get those libraries.(Fixes my borked #43)
> Add NuGet Packages into AboutForm

- src/managed/OpenLiveWriter.PostEditor/Updates/UpdateSettings.cs
The UpdateManager was overriding settings stored in the registry therefore we where not possible to switch onto the channel for CI build updates.
Remove logic that overwrites registry settings as it is no longer needed.
Set beta channel to come direct from blob store rather than via CDN.
Set the default value for beta updates when no registry key is present to be false.
> Beta update fix

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
You know when you start on something expecting it to be hard and then it works and you don't quite understand why. This is one of those.
Added the clientOptions.SupportsExtendedEntries attribute to the GoogleBloggerv3Client so that I could then start debugging how to get it working but the code seems to work as is once the capability is set.  Have to confess that this surprised me as I was expecting to have to do more work to get this up and running. New posts work, editing posts works, save local drafts works.
Anyone see anything that I missed?
> Add split post capability to GoogleBloggerV3Client

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
Add support for labels in Google Blogger.  I think this fixes #157.  Note that you can set your labels by providing a comma deliminated list but you cannot (yet) get a list of unique labels from the server so pressing the refresh button does nothing.
> Enable creation of blogger labels

- src/managed/OpenLiveWriter.PostEditor/BlogPostSupportingFileStorage.cs
The root cause here is that we accidentally made a breaking change when we removed the spell checking logic. We changed the CONTEXT_DICTIONARY_FILE constant from "context.tlx" to string.Empty. That means in the WriteSpellingContextDictionary() and ReadSpellingContextDictionary() methods, we were resolving a dictionary path as Path.Combine(SpellingContextDirectory, string.Empty); and then tried to create a FileStream on a directory. The fix here is simple, just change the dictionary filename back to "context.tlx".
> Issue #26 - OLW won't open local drafts or published posts, throws an UnauthorizedAccessException

- src/managed/OpenLiveWriter.Mshtml/MshtmlEditor.cs
This fixes #65.
Sometime during the completion callback for the document, **something** is mshtml is causing `IHtmlChangeSink.Notify` event to fire, causing setting the document to 'dirty', even if nothing really was changed. This PR fixes the problem by suppressing handling the Notify event during the completion callback. For more information, see the original issue #65.
> Preventing making the document 'dirty' during initialization

- build.cmd
- src/managed/PostBuild.CreateInstaller/createinstaller.cmd
For reasons lost in time my username on my laptop has spaces. That means
`%LocalAppData%` will also have spaces. That means calls to exes in
LocalAppData must be quoted. The `build.cmd` batch file will fail without
such quoted exe names. (Ditto `createinstaller.cmd`)
> Fix issue with spaces in username

- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
The Google Blogger v3 API has a limit to return only 500 items per
request. Each Blogger response returns a `NextPageToken` to get the next
500 items, so I added support to loop and download all posts and pages,
or stop early at a given maximum. You can see this by going to *File* >
*Open recent post* and then selecting a Google Blogger blog.
> Issue #247 - Support loading more than 500 Google Blogger posts

- src/managed/OpenLiveWriter.PostEditor/PostPropertyEditing/CategoryControl/TreeCategorySelector.cs
This PR addresses issue #389 
With this change, users can filter the categories tree view as expected. The category names will be filtered using a case-insensitive version of String.IndexOf, instead of String.StartsWith.
> Improved categories filter textbox filtering

- src/managed/OpenLiveWriter.CoreServices/Layout/GdiTextHelper.cs
This PR is supposed to fix issue #388 
Implementation details:
In the code, when parameter *UseMnemonics* was set to **true**, the DT_NOPREFIX flag was set, which actually turns mnemonics of.
The fix was to invert the if-condition.
--Neno
> Fix for issue #388 to handle Mnemonics correctly.

- src/managed/OpenLiveWriter.ApplicationFramework/CommandBarControl.cs
WinForms requires a few conventions to be met. All such forms/controls should have a default constructor.
> Fixed #409 by adding a default constructor to CommandBarControl.

- NuGet.config
Build would not work out of the box on my machine - possibly because global Nuget config was stored in %userprofile%\appdata\roaming.  Having a project-specific config will fix this issue
> Adding Nuget config file

- src/managed/OpenLiveWriter.BlogClient/Detection/BlogServiceDetector.cs
During blog client detection, if the HTML contains a `<link rel='service' type='application/atomsvc+xml'` element, the href will be parsed as an absolute URI, which fails if it's actually a relative URI. This change attempts to resolve the absolute URI from the relative URI, while also supporting the link being an absolute URI.
Unfortunately the URI is tested with an HTTP connection before returning, so I can't write unit tests for this change (without refactoring to make `BlogClientManager` a mockable interface, rather than static).
> Support atompub service link with relative url

- src/managed/OpenLiveWriter.BlogClient/Detection/BlogEditingTemplateDetector.cs
- src/managed/OpenLiveWriter.BlogClient/Detection/BlogPostRegionLocatorStrategy.cs
- src/managed/OpenLiveWriter.Extensibility/BlogClient/BlogClientException.cs
Blogs based on Blogger dynamic templates are essentially SPAs (Single Page Web Application) that uses AJAX to load the blog posts. With OLW's current template detection mechanism, the blog template cannot be detected for blogs using dynamic templates as the HTML content downloaded from server does not contain the post header/body. 
Currently when I try to setup a Blogger blog using Dynamic template on Open Live Writer, this is what happens:
1) I am authenticated using Blogger
2) Open Live Writer tries to download the template, fails.
3) OLW asks me if I want to download the template by publishing a temporary posts, I select "Yes"
4) OLW tries to download the template for about 3 minutes and 50 seconds (!) 
5) OLW tells me that "The blog theme couldn't be downloaded."
With this patch, OLW …
> Blogger dynamic templates : cut to the chase

- src/managed/OpenLiveWriter/OpenLiveWriter.exe.manifest
Fixes issue #585. Tested on Surface Book with 1440p secondary monitor, scaling appeared same on high DPI monitor and much better on lower DPI monitor.
> Add Per-Monitor DPI Support

- src/managed/OpenLiveWriter.BlogClient/Clients/BlogClientManager.cs
- src/managed/OpenLiveWriter.BlogClient/OpenLiveWriter.BlogClient.csproj
The commit that added Tistory support didn't add Tistory as a ClientType.  This fixes that oversight.
> Fix crash caused by addition of Tistory support

- src/managed/OpenLiveWriter.BlogClient/Clients/BlogClientManager.cs
- src/managed/OpenLiveWriter.BlogClient/Clients/BloggerAtomClient.cs
- src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs
- src/managed/OpenLiveWriter.BlogClient/OpenLiveWriter.BlogClient.csproj
- src/unmanaged/OpenLiveWriter.Ribbon/OpenLiveWriter.Ribbon.vcxproj
Fixes #786 _temporarily_.
This PR provides a temporary fix for [PR #786: Error 400 - The Remote server returned an error 
](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/786), which is caused by Google deprecating the Picasa API for photos.google.com.
Google has provided a [grace period](https://developers.google.com/picasa-web/docs/3.0/deprecation#extension), which extends until 15 March 2019, after which the Picasa API will be turned off for good.
The fix is commented with ``TODO: HACK:`` to emphasize that it won't last. Significant surgery on [GoogleBloggerv3Client.cs](https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs) is necessary to update to the new [Google Photos Library …
> Temporary fix for Picasa web requests

- src/managed/OpenLiveWriter.BlogClient/Detection/default.htm
- src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/PostHtmlEditingSettings.cs
Set MSHTML into IE9 emulation mode by adjusting X-UA-Compatible in the editing template. IE10 Standards modes and higher no longer support Element Behaviors and HTML components (read more: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/hh801216(v=vs.85)), and as such, table resizing, cell selection, and automatic detection of tables in source, amongst other features, ceased to function.
This PR alters PostHtmlEditingSettings to ensure blog editing templates are placed into EmulateIE9 mode, as well as altering the default template to enable EmulateIE9 mode. This may break in-theme editing of blogs which rely on complex CSS3 styles, however this would be as far as we can get without completely restructuring how editing behaviors …
> Set MSHTML IE9 Emulation Mode (fixes #829 and others)

- src/managed/OpenLiveWriter.PostEditor/PostPropertyEditing/PostPropertiesBandControl.Designer.cs
- src/managed/OpenLiveWriter.PostEditor/PostPropertyEditing/PostPropertiesBandControl.cs
- src/managed/OpenLiveWriter.PostEditor/PostPropertyEditing/PostPropertiesBandControl.resx
Make the Parent drop-down for Page settings expand to fill all horizontal space, rather than having a static width. This allows page titles longer than the drop-down's previous width to be read. Fixes #828. Screenshot of new drop-down below:
> Make Page Parent drop-down fill horizontal space (fixes #828)

- src/managed/OpenLiveWriter.PostEditor/Updates/UpdateManager.cs
Seems #838 is caused by Squirrel thinking that the current public release is 'newer' than the development release, even though the version number is lower. This change compares the two versions, and will only attempt the Squirrel update if the version number is equal or newer.
> UpdateManager: don't update if update is older than currently running version (fixes #838)

- src/managed/OpenLiveWriter.PostEditor/Video/VideoProvidersB2.xml
- src/managed/OpenLiveWriter.PostEditor/Video/WebVideoSource.cs
Related to issue #849  
In the 'Insert Video from the web' tab, now we get a preview of the video of youtube URLs containing https and youtu.be and the video can be played too using the HTML5 player in the preview tab. :)
> Insert from web - allowing YouTube URLs

- src/managed/OpenLiveWriter.PostEditor/OpenPost/OpenPostForm.cs
Related to issue #820.
added a KeyEventhandler to handle whenever ```ALT + S``` is pressed, and to show the dropped down item count box (combo box).
> Enable focus on the item count box 

- src/managed/OpenLiveWriter.PostEditor/BlogPostEditingManager.cs
Related to issue #303 
Now, a new window will not open when the posts are empty and the single window is selected in the preferences.
> New window is opened when Single window is selected in preferences

- src/managed/OpenLiveWriter.PostEditor/PostHtmlEditing/ImageInsertionManager.cs
Related to issue #691 
This fixes the issue when multiple images are selected in the Insert Picture. Now we are able to get a line between the images where text can be entered.
> Line between images so that text can be entered
